insert into CATEGORY (name) values ('animals');
insert into CATEGORY (name) values ('furniture');
insert into CATEGORY (name) values ('fruits');
insert into CATEGORY (name) values ('vegetables');
insert into CATEGORY (name) values ('sport');
insert into CATEGORY (name) values ('flowers');
insert into CATEGORY (name) values ('clothes');
insert into CATEGORY (name) values ('dishes');
insert into CATEGORY (name) values ('singers');
insert into CATEGORY (name) values ('festivals');

insert into MAPPING (category_id, number, word) values (1,1,'Mouse');
insert into MAPPING (category_id, number, word) values (1,2,'Cat');
insert into MAPPING (category_id, number, word) values (1,3,'Dog');
insert into MAPPING (category_id, number, word) values (1,4,'Elephant');
insert into MAPPING (category_id, number, word) values (1,5,'Crocodile');
insert into MAPPING (category_id, number, word) values (1,6,'Bat');
insert into MAPPING (category_id, number, word) values (1,7,'Frog');
insert into MAPPING (category_id, number, word) values (1,8,'Crow');
insert into MAPPING (category_id, number, word) values (1,9,'Tiger');
insert into MAPPING (category_id, number, word) values (1,10,'Chipmunk');
insert into MAPPING (category_id, number, word) values (1,11,'Pig');
insert into MAPPING (category_id, number, word) values (1,12,'Parakeet');
insert into MAPPING (category_id, number, word) values (1,13,'Dugong');
insert into MAPPING (category_id, number, word) values (1,14,'Lizard');
insert into MAPPING (category_id, number, word) values (1,15,'Reindeer');
insert into MAPPING (category_id, number, word) values (1,16,'Ewe');
insert into MAPPING (category_id, number, word) values (1,17,'Cow');
insert into MAPPING (category_id, number, word) values (1,18,'Muskrat');
insert into MAPPING (category_id, number, word) values (1,19,'Chamois');
insert into MAPPING (category_id, number, word) values (1,20,'Porcupine');

insert into MAPPING (category_id, number, word) values (2,1,'Chair');
insert into MAPPING (category_id, number, word) values (2,2,'Table');
insert into MAPPING (category_id, number, word) values (2,3,'Cabinet');
insert into MAPPING (category_id, number, word) values (2,4,'Bed');
insert into MAPPING (category_id, number, word) values (2,5,'Desk');
insert into MAPPING (category_id, number, word) values (2,6,'Futon');
insert into MAPPING (category_id, number, word) values (2,7,'Lamp');
insert into MAPPING (category_id, number, word) values (2,8,'Mirror');
insert into MAPPING (category_id, number, word) values (2,9,'Pillow');
insert into MAPPING (category_id, number, word) values (2,10,'Sofa');
insert into MAPPING (category_id, number, word) values (2,11,'Secretary');
insert into MAPPING (category_id, number, word) values (2,12,'Wardrobe');
insert into MAPPING (category_id, number, word) values (2,13,'Waste Basket');
insert into MAPPING (category_id, number, word) values (2,14,'Carpet');
insert into MAPPING (category_id, number, word) values (2,15,'Chest');
insert into MAPPING (category_id, number, word) values (2,16,'Crib');
insert into MAPPING (category_id, number, word) values (2,17,'Easel');
insert into MAPPING (category_id, number, word) values (2,18,'Fauteuil');
insert into MAPPING (category_id, number, word) values (2,19,'Hall Tree');
insert into MAPPING (category_id, number, word) values (2,20,'Hammock');

insert into MAPPING (category_id, number, word) values (3,1,'Apple');
insert into MAPPING (category_id, number, word) values (3,2,'Apricot');
insert into MAPPING (category_id, number, word) values (3,3,'Avocado');
insert into MAPPING (category_id, number, word) values (3,4,'Banana');
insert into MAPPING (category_id, number, word) values (3,5,'Berry');
insert into MAPPING (category_id, number, word) values (3,6,'Blackberry');
insert into MAPPING (category_id, number, word) values (3,7,'Blood Orange');
insert into MAPPING (category_id, number, word) values (3,8,'Blueberry');
insert into MAPPING (category_id, number, word) values (3,9,'Boysenberry');
insert into MAPPING (category_id, number, word) values (3,10,'Breadfruit');
insert into MAPPING (category_id, number, word) values (3,11,'Grape');
insert into MAPPING (category_id, number, word) values (3,12,'Grapefruit');
insert into MAPPING (category_id, number, word) values (3,13,'Guava');
insert into MAPPING (category_id, number, word) values (3,14,'Honeydew');
insert into MAPPING (category_id, number, word) values (3,15,'Jackfruit');
insert into MAPPING (category_id, number, word) values (3,16,'Kiwi');
insert into MAPPING (category_id, number, word) values (3,17,'Kumquat');
insert into MAPPING (category_id, number, word) values (3,18,'Lemon');
insert into MAPPING (category_id, number, word) values (3,19,'Lime');
insert into MAPPING (category_id, number, word) values (3,20,'Lingonberry');

insert into MAPPING (category_id, number, word) values (4,1,'Capers');
insert into MAPPING (category_id, number, word) values (4,2,'Carrot');
insert into MAPPING (category_id, number, word) values (4,3,'Peppers');
insert into MAPPING (category_id, number, word) values (4,4,'Celeriac');
insert into MAPPING (category_id, number, word) values (4,5,'Celery');
insert into MAPPING (category_id, number, word) values (4,6,'Chard');
insert into MAPPING (category_id, number, word) values (4,7,'Garlic');
insert into MAPPING (category_id, number, word) values (4,8,'Ginger');
insert into MAPPING (category_id, number, word) values (4,9,'Gourd');
insert into MAPPING (category_id, number, word) values (4,10,'Green Bean');
insert into MAPPING (category_id, number, word) values (4,11,'Greens');
insert into MAPPING (category_id, number, word) values (4,12,'Okra');
insert into MAPPING (category_id, number, word) values (4,13,'Olive');
insert into MAPPING (category_id, number, word) values (4,14,'Onion');
insert into MAPPING (category_id, number, word) values (4,15,'Parsley');
insert into MAPPING (category_id, number, word) values (4,16,'Parsnip');
insert into MAPPING (category_id, number, word) values (4,17,'Pattypan Squash');
insert into MAPPING (category_id, number, word) values (4,18,'Potato');
insert into MAPPING (category_id, number, word) values (4,19,'Peanut');
insert into MAPPING (category_id, number, word) values (4,20,'Peapod');

insert into MAPPING (category_id, number, word) values (5,1,'Softball');
insert into MAPPING (category_id, number, word) values (5,2,'American Football');
insert into MAPPING (category_id, number, word) values (5,3,'Squash');
insert into MAPPING (category_id, number, word) values (5,4,'Rowing');
insert into MAPPING (category_id, number, word) values (5,5,'Baseball');
insert into MAPPING (category_id, number, word) values (5,6,'Figure Skating');
insert into MAPPING (category_id, number, word) values (5,7,'Lacrosse');
insert into MAPPING (category_id, number, word) values (5,8,'Equestrianism');
insert into MAPPING (category_id, number, word) values (5,9,'Taekwondo');
insert into MAPPING (category_id, number, word) values (5,10,'Track And Field Athletics');
insert into MAPPING (category_id, number, word) values (5,11,'Water Polo');
insert into MAPPING (category_id, number, word) values (5,12,'Horse Racing');
insert into MAPPING (category_id, number, word) values (5,13,'Skiing');
insert into MAPPING (category_id, number, word) values (5,14,'Ultimate');
insert into MAPPING (category_id, number, word) values (5,15,'Polo');
insert into MAPPING (category_id, number, word) values (5,16,'Cricket');
insert into MAPPING (category_id, number, word) values (5,17,'Rugby League');
insert into MAPPING (category_id, number, word) values (5,18,'Field Hockey');
insert into MAPPING (category_id, number, word) values (5,19,'Ice Hockey');
insert into MAPPING (category_id, number, word) values (5,20,'Tennis');

insert into MAPPING (category_id, number, word) values (6,1,'Gayfeather');
insert into MAPPING (category_id, number, word) values (6,2,'Transvaal Daisy');
insert into MAPPING (category_id, number, word) values (6,3,'Lotus');
insert into MAPPING (category_id, number, word) values (6,4,'Prairie Gentian');
insert into MAPPING (category_id, number, word) values (6,5,'Gladiolus');
insert into MAPPING (category_id, number, word) values (6,6,'Columbine');
insert into MAPPING (category_id, number, word) values (6,7,'Tulip');
insert into MAPPING (category_id, number, word) values (6,8,'Touch-Me-Not');
insert into MAPPING (category_id, number, word) values (6,9,'Nerine');
insert into MAPPING (category_id, number, word) values (6,10,'Rose');
insert into MAPPING (category_id, number, word) values (6,11,'Anemone');
insert into MAPPING (category_id, number, word) values (6,12,'Daffodil');
insert into MAPPING (category_id, number, word) values (6,13,'Daisy Family');
insert into MAPPING (category_id, number, word) values (6,14,'Cherry Blossom');
insert into MAPPING (category_id, number, word) values (6,15,'Coneflower');
insert into MAPPING (category_id, number, word) values (6,16,'Dendrobium');
insert into MAPPING (category_id, number, word) values (6,17,'Moth Orchids');
insert into MAPPING (category_id, number, word) values (6,18,'English Marigold');
insert into MAPPING (category_id, number, word) values (6,19,'Lavender');
insert into MAPPING (category_id, number, word) values (6,20,'Feverfew');

insert into MAPPING (category_id, number, word) values (7,1,'Cummerbund');
insert into MAPPING (category_id, number, word) values (7,2,'Suit');
insert into MAPPING (category_id, number, word) values (7,3,'Bikini');
insert into MAPPING (category_id, number, word) values (7,4,'Shorts');
insert into MAPPING (category_id, number, word) values (7,5,'Sweatshirt');
insert into MAPPING (category_id, number, word) values (7,6,'Gown');
insert into MAPPING (category_id, number, word) values (7,7,'Belt');
insert into MAPPING (category_id, number, word) values (7,8,'Pajamas');
insert into MAPPING (category_id, number, word) values (7,9,'Thong');
insert into MAPPING (category_id, number, word) values (7,10,'Overalls');
insert into MAPPING (category_id, number, word) values (7,11,'Swimming Shorts');
insert into MAPPING (category_id, number, word) values (7,12,'Slippers');
insert into MAPPING (category_id, number, word) values (7,13,'Sunglasses');
insert into MAPPING (category_id, number, word) values (7,14,'Sandals');
insert into MAPPING (category_id, number, word) values (7,15,'Cargos');
insert into MAPPING (category_id, number, word) values (7,16,'Top');
insert into MAPPING (category_id, number, word) values (7,17,'Shawl');
insert into MAPPING (category_id, number, word) values (7,18,'Nightgown');
insert into MAPPING (category_id, number, word) values (7,19,'Skirt');
insert into MAPPING (category_id, number, word) values (7,20,'Sarong');

insert into MAPPING (category_id, number, word) values (8,1,'Coffee');
insert into MAPPING (category_id, number, word) values (8,2,'Sushi');
insert into MAPPING (category_id, number, word) values (8,3,'Herb');
insert into MAPPING (category_id, number, word) values (8,4,'Beef');
insert into MAPPING (category_id, number, word) values (8,5,'Garlic');
insert into MAPPING (category_id, number, word) values (8,6,'Stuffing');
insert into MAPPING (category_id, number, word) values (8,7,'Bun');
insert into MAPPING (category_id, number, word) values (8,8,'Lamb And Mutton');
insert into MAPPING (category_id, number, word) values (8,9,'Maize');
insert into MAPPING (category_id, number, word) values (8,10,'Meatball');
insert into MAPPING (category_id, number, word) values (8,11,'Tapas');
insert into MAPPING (category_id, number, word) values (8,12,'Tomato');
insert into MAPPING (category_id, number, word) values (8,13,'Peanut');
insert into MAPPING (category_id, number, word) values (8,14,'Coconut');
insert into MAPPING (category_id, number, word) values (8,15,'French Fries');
insert into MAPPING (category_id, number, word) values (8,16,'Bean');
insert into MAPPING (category_id, number, word) values (8,17,'Strawberry');
insert into MAPPING (category_id, number, word) values (8,18,'Eggplant');
insert into MAPPING (category_id, number, word) values (8,19,'Porridge');
insert into MAPPING (category_id, number, word) values (8,20,'Soybean');

insert into MAPPING (category_id, number, word) values (9,1,'Madonna');
insert into MAPPING (category_id, number, word) values (9,2,'Ray Charles');
insert into MAPPING (category_id, number, word) values (9,3,'Frank Sinatra');
insert into MAPPING (category_id, number, word) values (9,4,'Demi Lovato');
insert into MAPPING (category_id, number, word) values (9,5,'Gwen Stefani');
insert into MAPPING (category_id, number, word) values (9,6,'Ariana Grande');
insert into MAPPING (category_id, number, word) values (9,7,'Jennifer Lopez');
insert into MAPPING (category_id, number, word) values (9,8,'Jessie J');
insert into MAPPING (category_id, number, word) values (9,9,'Bruno Mars');
insert into MAPPING (category_id, number, word) values (9,10,'Barbra Streisand');
insert into MAPPING (category_id, number, word) values (9,11,'Nicki Minaj');
insert into MAPPING (category_id, number, word) values (9,12,'Britney Spears');
insert into MAPPING (category_id, number, word) values (9,13,'Perrie Edwards');
insert into MAPPING (category_id, number, word) values (9,14,'Cher');
insert into MAPPING (category_id, number, word) values (9,15,'Justin Timberlake');
insert into MAPPING (category_id, number, word) values (9,16,'Tina Turner');
insert into MAPPING (category_id, number, word) values (9,17,'Bob Dylan');
insert into MAPPING (category_id, number, word) values (9,18,'Michael Jackson');
insert into MAPPING (category_id, number, word) values (9,19,'Taylor Swift');
insert into MAPPING (category_id, number, word) values (9,20,'Elvis Presley');

insert into MAPPING (category_id, number, word) values (10,1,'Reading And Leeds Festivals');
insert into MAPPING (category_id, number, word) values (10,2,'Pitchfork Music Festival');
insert into MAPPING (category_id, number, word) values (10,3,'Electric Forest Festival');
insert into MAPPING (category_id, number, word) values (10,4,'All Good Music Festival');
insert into MAPPING (category_id, number, word) values (10,5,'The Fest');
insert into MAPPING (category_id, number, word) values (10,6,'Big Music Fest');
insert into MAPPING (category_id, number, word) values (10,7,'Lightning In A Bottle');
insert into MAPPING (category_id, number, word) values (10,8,'Electric Daisy Carnival');
insert into MAPPING (category_id, number, word) values (10,9,'Coachella Valley Music And Arts Festival');
insert into MAPPING (category_id, number, word) values (10,10,'Teknival');
insert into MAPPING (category_id, number, word) values (10,11,'Shaky Knees Music Festival');
insert into MAPPING (category_id, number, word) values (10,12,'Summer Camp Music Festival');
insert into MAPPING (category_id, number, word) values (10,13,'Lockn" Festival');
insert into MAPPING (category_id, number, word) values (10,14,'Firefly Music Festival');
insert into MAPPING (category_id, number, word) values (10,15,'Creamfields');
insert into MAPPING (category_id, number, word) values (10,16,'Newport Folk Festival');
insert into MAPPING (category_id, number, word) values (10,17,'Electric Zoo');
insert into MAPPING (category_id, number, word) values (10,18,'Us Festival');
insert into MAPPING (category_id, number, word) values (10,19,'Download Festival');
insert into MAPPING (category_id, number, word) values (10,20,'Woodstock');

